// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiVideoGamesExcercise.Entities;

#nullable disable

namespace RestApiVideoGamesExcercise.Migrations
{
    [DbContext(typeof(VideoGamesContext))]
    [Migration("20230112184239_InitialMigration_After_Scaffolding")]
    partial class InitialMigration_After_Scaffolding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestApiVideoGamesExcercise.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("VideoGameStudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameStudioId");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Counter Strike",
                            Price = 50m,
                            Size = 2000,
                            VideoGameStudioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pro Evolution",
                            Price = 55m,
                            Size = 2100,
                            VideoGameStudioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "FIFA",
                            Price = 60m,
                            Size = 2200,
                            VideoGameStudioId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Call of Duty",
                            Price = 65m,
                            Size = 2300,
                            VideoGameStudioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blur",
                            Price = 70m,
                            Size = 2400,
                            VideoGameStudioId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Assasin Creed",
                            Price = 75m,
                            Size = 2500,
                            VideoGameStudioId = 1
                        });
                });

            modelBuilder.Entity("RestApiVideoGamesExcercise.Models.VideoGameStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VideoGameStudio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            StudioName = "XXX"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            StudioName = "YYY"
                        });
                });

            modelBuilder.Entity("RestApiVideoGamesExcercise.Models.VideoGame", b =>
                {
                    b.HasOne("RestApiVideoGamesExcercise.Models.VideoGameStudio", "VideoGameStudio")
                        .WithMany("VideoGames")
                        .HasForeignKey("VideoGameStudioId")
                        .IsRequired()
                        .HasConstraintName("FK_VideoGames_VideoGameStudio");

                    b.Navigation("VideoGameStudio");
                });

            modelBuilder.Entity("RestApiVideoGamesExcercise.Models.VideoGameStudio", b =>
                {
                    b.Navigation("VideoGames");
                });
#pragma warning restore 612, 618
        }
    }
}
